version: "3.5"

services:
  oracle12c:
    image: store/oracle/database-enterprise:12.2.0.1
    container_name: oracle12c
    environment:
      - ORACLE_ALLOW_REMOTE=true
    volumes:
      - /home/oracle/oradata:/opt/oracle/oradata # persistent oracle database data.
    ports:
      - 1521:1521
     
   